language: python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pip --upgrade
  - pip install Cython==0.24.1
  - pip install .[dev]

script: make test

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

