language: python

python:
  - 3.4
  - 3.5

install:
  - pip install pip --upgrade
  - pip install .[dev] --verbose

script: make test

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

